import { redirect } from 'next/navigation'
import { AlertCircle } from 'lucide-react'
import { Card } from '@roomlink/ui'
import { requireGuestSession } from '@/server/require-guest-session'
import { resolveQrCode } from '@/server/services/session.service'
import { SessionNotActiveError } from '@/server/errors'
import { MobileForm } from './mobile-form'

export const dynamic = 'force-dynamic'

/**
 * The entire QR flow. The QR (`code_value`, opaque, already generated by
 * the Hotel Admin module) only ever identifies hotel + room — it never
 * grants access by itself; a guest must still verify the mobile number
 * Front Office activated the stay with. If the visiting browser already
 * carries a valid session cookie for *this* room, skip straight to Home
 * rather than asking for verification again (re-scanning mid-stay should
 * be a no-op, not a re-login).
 */
export default async function QrLandingPage({ params }: { params: { code: string } }) {
  let existingRoomId: string | null = null
  try {
    existingRoomId = (await requireGuestSession()).roomId
  } catch {
    // No valid session yet — fall through to mobile-number verification below.
  }

  let landing: Awaited<ReturnType<typeof resolveQrCode>> | null = null
  let errorMessage: string | null = null
  try {
    landing = await resolveQrCode(params.code)
  } catch (error) {
    if (error instanceof SessionNotActiveError) {
      errorMessage = error.message
    } else {
      throw error
    }
  }

  if (existingRoomId && landing && existingRoomId === landing.roomId) {
    redirect('/home')
  }

  if (errorMessage) {
    return (
      <main className="flex min-h-screen items-center justify-center px-6">
        <Card className="max-w-sm space-y-3 p-8 text-center">
          <AlertCircle className="mx-auto h-10 w-10 text-amber-500" aria-hidden />
          <p className="text-sm text-slate-700">{errorMessage}</p>
          <p className="text-xs text-slate-400">Please contact the front desk for help.</p>
        </Card>
      </main>
    )
  }

  return (
    <main className="flex min-h-screen items-center justify-center px-6">
      <Card className="w-full max-w-sm p-8">
        <MobileForm codeValue={params.code} hotelName={landing!.hotelName} roomNumber={landing!.roomNumber} />
      </Card>
    </main>
  )
}
